/** @type {import('tailwindcss').Config} */
export default {
  content: [
    './src/**/*.{astro,html,js,jsx,ts,tsx}',
  ],
  safelist: [
    'col-span-1',
    'col-span-2',
    'grid-cols-1',
    'grid-cols-2',
    'grid-cols-3',
    'grid',
    'gap-3',
    'gap-4',
    'gap-6',
    'min-w-0',
    'overflow-x-hidden',
  ],
  theme: {
    extend: {
      colors: {
        bg: '#06060e',
        surface: '#0c0c1a',
        raised: '#131325',
        hover: '#1a1a30',
        border: '#1e1e38',
        'border-subtle': '#141428',
        'ink-primary': '#ededf5',
        'ink-secondary': '#7a7a95',
        'ink-muted': '#3a3a52',
        accent: '#f0a500',
        'accent-dim': 'rgba(240,165,0,0.08)',
        'accent-hover': '#fbbf24',
        ok: '#22c55e',
        fail: '#ef4444',
        warn: '#f59e0b',
      },
      fontFamily: {
        heading: ['Syne', 'sans-serif'],
        body: ['"DM Sans"', 'sans-serif'],
        mono: ['"JetBrains Mono"', 'monospace'],
      },
      spacing: {
        'sidebar': '240px',
        'topbar': '56px',
      },
      borderRadius: {
        DEFAULT: '12px',
        sm: '8px',
        lg: '16px',
        xl: '20px',
      },
      animation: {
        'scale-in': 'scale-in 0.3s cubic-bezier(0.4,0,0.2,1) forwards',
        'slide-right': 'slide-in-right 0.35s cubic-bezier(0.4,0,0.2,1) forwards',
        'slide-down': 'slide-down 0.25s ease-out forwards',
        'float': 'float 3s ease-in-out infinite',
        'glow': 'glow-pulse 2s ease-in-out infinite',
      },
      keyframes: {
        'scale-in': { from: { opacity: '0', transform: 'scale(0.95)' }, to: { opacity: '1', transform: 'scale(1)' } },
        'slide-in-right': { from: { opacity: '0', transform: 'translateX(16px)' }, to: { opacity: '1', transform: 'translateX(0)' } },
        'slide-down': { from: { opacity: '0', transform: 'translateY(-8px)' }, to: { opacity: '1', transform: 'translateY(0)' } },
        'float': { '0%, 100%': { transform: 'translateY(0)' }, '50%': { transform: 'translateY(-4px)' } },
        'glow-pulse': { '0%, 100%': { opacity: '0.5' }, '50%': { opacity: '1' } },
      },
    },
  },
  plugins: [],
}
